### ISSUE TITLE
Problems when running on dataloader on MacOS 14.4.1 

### ISSUE THREAD

**Issue by medeag** [forcedotcom/dataloader#1073]
When opening the data loader it shows empty screen

2. Click on dataloader
4. See that screen is empty

**Expected behavior**
The screen should provide actions.

**Screenshots**
![555f04f7-be78-4955-99b7-3dab15e1954b](https://github.com/forcedotcom/dataloader/assets/3065166/2922b9c0-26d8-49f1-becc-513a3e82df4e)

**Desktop (please complete the following information):**
 - OS:  MacOS Sonoma
 - Version 14.4.1

**Comment by medeag** [comment]
Data loader's version is 60.0.2

**Comment by medeag** [comment]
It is light
<img width="703" alt="Screenshot 2024-04-03 at 20 21 44" src="https://github.com/forcedotcom/dataloader/assets/3065166/ccec79bb-2458-4637-8f05-f6e5648495da">

This is what i see if i run it using dataloader_console:

2024-04-03 20:22:24,819 INFO  [main] config.Config createDir (Config.java:1496) - Config folder already exists: /Applications/dataloader_v60.0.2/configs
2024-04-03 20:22:24,821 INFO  [main] config.Config getInstance (Config.java:1529) - Looking for file in config path: /Applications/dataloader_v60.0.2/configs/config.properties
2024-04-03 20:22:24,821 INFO  [main] config.Config getInstance (Config.java:1560) - User config is found in /Applications/dataloader_v60.0.2/configs/config.properties
2024-04-03 20:22:24,824 INFO  [main] config.LastRun load (LastRun.java:87) - Last run info will be saved in file: /Applications/dataloader_v60.0.2/configs/insert_lastRun.properties
2024-04-03 20:22:24,824 INFO  [main] config.Config getInstance (Config.java:1567) - The controller config has been initialized

**Comment by ashitsalesforce** [comment]
Try Dark Appearance on your desktop. If that does not fix, try [v59.0.0](https://github.com/forcedotcom/dataloader/releases/tag/v59.0.0).

v60.0.x use the same version of Eclipse SWT, the library used to render Data Loader UI. v59.0.0 uses an earlier version of SWT.

**Comment by smeeGit** [comment]
I'm having the same issue on a MBP M3 Pro - I've tried each of the v60 versions and I've tried switching system preference from Dark, to Light. As a follow up from @medeag's last response, I tried v59.0.0. I verified the MD5 was the same as was listed on the downloads page and here's a screenshot of the app loaded
![image](https://github.com/forcedotcom/dataloader/assets/1044747/6baf2826-d113-449e-acb8-00381cea1ce7)

This is the "Settings" window: 
![image](https://github.com/forcedotcom/dataloader/assets/1044747/991031ec-38df-4bdb-9a4d-97c77200411a)

**Comment by ashitsalesforce** [comment]
Hi @smeeGit , thanks for experimenting and sharing the details of the issue. It is not reproducible on MacAir M1, with MacOS 14.4.1 and no one has reported similar issues before. Wondering if it has to do with M3 graphics. It will be good to know which Mac hardware @medeag has.

Can you share data loader console output as you start the app?

**Comment by ashitsalesforce** [comment]
Hi @smeeGit , we do not have a readily available Mac M3 to try and reproduce the issue. So, we may have to do a few experiments with your help. I am attaching a local build of Data Loader that does not do any font settings for you to try. Let us know if it addresses the issue.

[dataloader_v60.0.2.zip](https://github.com/forcedotcom/dataloader/files/14940147/dataloader_v60.0.2.zip)
MD5 (dataloader_v60.0.2.zip) = 18ea3a624c3470669ff62d100620c598

**Comment by nrlakin** [comment]
I am having the same issue with v60.0.2 and 59.0.0, with both an x86 max and an M2 Mac. Both are running OSX 14.4.1.

**Comment by ashitsalesforce** [comment]
Hi @nrlakin, M2 has been on the market for a while. So, that eliminates new hardware theory. I have a M1 with OSX 14.4.1 where both of these releases run fine. So, we can't pin it to OSX 14.4.1. Can you share the console output of the Data Loader? Perhaps there is a warning when the issue occurs.

**Comment by ashitsalesforce** [comment]
@medeag , @nrlakin , @smeeGit , this turns out to be an issue with the latest JRE/JDK from Eclipse/Adaptium Temurin JDK/JRE. The issue did not exist in the previous release. For example if you are using Temurin JRE [17.0.10+7](https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.10%2B7), switch to Temurin JRE [17.0.9+9](https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.9%2B9) or switch to another JRE/JDK altogether.

**Comment by nrlakin** [comment]
Thank you, @ashitsalesforce! I was using OpenJDK 17.0.10, but downgrading to 17.0.9 fixed the issue for me.

**Comment by ashitsalesforce** [comment]
Good to hear that the issue is resolved. I will close it.

**Comment by jamesongithub** [comment]
seeing this also on openjdk 21.0.2
dataloader v60.0.02

![image](https://github.com/forcedotcom/dataloader/assets/4452738/5cd5c532-902f-4d46-99fb-6cc135fd4022)

saw this was fixed in #1100 is there a new jar for it?

**Comment by jamesongithub** [comment]
thanks for the release link. it seems to be hidden on the repo.

i tried jdk 21.0.2 and jdk 17.0.11 which each of dataloader 58.0.4, 59.0.0 and 60.0.2 and it's still not working

```
java --version
openjdk 17.0.11 2024-04-16
OpenJDK Runtime Environment Homebrew (build 17.0.11+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.11+0, mixed mode, sharing)
kinetica-m2mbp-jyang:v60.0.2 jyang$ java -jar dataloader-60.0.2.jar 

*************************************************************************
**                                                                     **
**              Salesforce Data Loader                                 **
**              ======================                                 **
**                                                                     **
**  Data Loader v60 is a Salesforce supported Open Source project to   **
**  help you import data to and export data from your Salesforce org.  **
**  It requires Java JRE 17 or later to run.                           **
**                                                                     **
**  Github Project Url:                                                **
**       https://github.com/forcedotcom/dataloader                     **
**  Salesforce Documentation:                                          **
**       https://help.salesforce.com/articleView?id=data_loader.htm    **
**                                                                     **
*************************************************************************


2024-04-29 16:40:04,675 INFO  [main] config.Config createDir (Config.java:1496) - Config folder already exists: /Users/jyang/dataloader/v60.0.2/configs
2024-04-29 16:40:04,676 INFO  [main] config.Config getInstance (Config.java:1529) - Looking for file in config path: /Users/jyang/dataloader/v60.0.2/configs/config.properties
2024-04-29 16:40:04,676 INFO  [main] config.Config getInstance (Config.java:1560) - User config is found in /Users/jyang/dataloader/v60.0.2/configs/config.properties
2024-04-29 16:40:04,679 INFO  [main] config.LastRun load (LastRun.java:87) - Last run info will be saved in file: /Users/jyang/dataloader/v60.0.2/configs/insert_lastRun.properties
2024-04-29 16:40:04,679 INFO  [main] config.Config getInstance (Config.java:1567) - The controller config has been initialized
```

**Comment by ashitsalesforce** [comment]
Try this [patch](https://github.com/forcedotcom/dataloader/files/15042179/dataloader_v60.0.2.zip).

**Comment by jamesongithub** [comment]
hmm still blank...

could it be something else?

```
$ md5 dataloader-60.0.2.jar 
MD5 (dataloader-60.0.2.jar) = 9b4cb8e955e3f11f3e4f022a99821540
$ java --version
openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment Homebrew (build 21.0.2)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.2, mixed mode, sharing)

java -jar dataloader-60.0.2.jar 

*************************************************************************
**                                                                     **
**              Salesforce Data Loader                                 **
**              ======================                                 **
**                                                                     **
**  Data Loader v60 is a Salesforce supported Open Source project to   **
**  help you import data to and export data from your Salesforce org.  **
**  It requires Java JRE 17 or later to run.                           **
**                                                                     **
**  Github Project Url:                                                **
**       https://github.com/forcedotcom/dataloader                     **
**  Salesforce Documentation:                                          **
**       https://help.salesforce.com/articleView?id=data_loader.htm    **
**                                                                     **
*************************************************************************


2024-04-29 17:05:38,453 INFO  [main] config.Config createDir (Config.java:1519) - Config folder already exists: /Users/jyang/dataloader/v60.0.2-patch/configs
2024-04-29 17:05:38,454 INFO  [main] config.Config getInstance (Config.java:1552) - Looking for file in config path: /Users/jyang/dataloader/v60.0.2-patch/configs/config.properties
2024-04-29 17:05:38,455 INFO  [main] config.Config getInstance (Config.java:1583) - User config is found in /Users/jyang/dataloader/v60.0.2-patch/configs/config.properties
2024-04-29 17:05:38,457 INFO  [main] config.LastRun load (LastRun.java:87) - Last run info will be saved in file: /Users/jyang/dataloader/v60.0.2-patch/configs/insert_lastRun.properties
2024-04-29 17:05:38,458 INFO  [main] config.Config getInstance (Config.java:1590) - The controller config has been initialized

```

**Comment by ashitsalesforce** [comment]
The root-cause of the issue is that SWT 4.31 used by Data Loader v60.0.2 has a bug that got fixed in SWT 4.32M1. Can you check that your data loader installation folder has SWT 4.32M1 jar (swtmac_aarch64-4.32M1.jar)?

**Comment by jamesongithub** [comment]
ah ok it's still getting 4.31 even with the patch. can i configure it to download 4.32? or just manually download it?

**Comment by ashitsalesforce** [comment]
You can use the [one](https://github.com/forcedotcom/dataloader/blob/master/local-proj-repo/local/swt/swtmac_aarch64/4.32M1/swtmac_aarch64-4.32M1.jar) I checked in.

**Comment by ashitsalesforce** [comment]
It fixes MANIFEST issues found in the original 4.32M1.

**Comment by jamesongithub** [comment]
thanks! it's working now if i use 4.32M1 

it looks like the installer was still pulling in 4.31

**Comment by jamesongithub** [comment]
> Good to hear. Apologies for giving you incorrect patch pointer.

no worries! thanks for your help

**Comment by ashitsalesforce** [comment]
Hi @jamesongithub , [v61.0.0](https://github.com/forcedotcom/dataloader/releases/tag/v61.0.0) contains the fix.

**Comment by jamesongithub** [comment]
> Hi @jamesongithub , [v61.0.0](https://github.com/forcedotcom/dataloader/releases/tag/v61.0.0) contains the fix.

thanks @ashitsalesforce this works out of the box now.

**Comment by ashitsalesforce** [comment]
Thanks for verifying @jamesongithub
