### ISSUE TITLE
Error When Installing Data Loader (v58.0.3) on Windows 11 Even Though OpenJDK (17.0.8+7) is Installed

### ISSUE THREAD

**Issue by ricardohuang81** [forcedotcom/dataloader#740]
**Describe the bug**
1. In **Windows 11**, I installed **Azul Zulu Builds of OpenJDK 17.0.8+7 (latest LTS) Windows 64-bit MSI**
2. Extracted the file in C:\Program Files
3. Downloaded the **Summer '23 Data Loader Release for for macOS and Windows (v58.0.3)** Data Loader file
4. Extracted the file in C:\Program Files
5. Clicked the **Install.bat** file
6. Then I received an error I don't understand and don't know how to get past, see screenshot below

**To Reproduce**
1. Install **Azul Zulu Builds of OpenJDK 17.0.8+7 (latest LTS) Windows 64-bit MSI** file from the [Download Azul JDKs site](https://www.azul.com/downloads/?package=jdk#zulu) site
2. Extract Azul Zulu Builds of OpenJDK 17.0.8+7 (latest LTS) Windows 64-bit MSI in C:\Program Files
3. Download **Summer '23 Data Loader Release for for macOS and Windows (v58.0.3)** zip file from this [Salesforce Developers site](https://developer.salesforce.com/tools/data-loader)
4. Extract **Summer '23 Data Loader Release for for macOS and Windows (v58.0.3)** zip file in C:\Program Files
5. Click the **Install.bat** file
6. When command prompt opens up, press **Enter** to install Data Loader in the default directory
7. The error from screenshot arises

**Expected behavior**
Command Prompt opens up after clicking Install.bat and the error in screenshot shows up

**Screenshots**
![Dataloader Error](https://github.com/forcedotcom/dataloader/assets/25620842/8ea8d562-8cfb-4cad-bc8e-daad739e6021)

**Desktop (please complete the following information):**
- OS: Windows 11

**Comment by ashitsalesforce** [comment]
Hi @ricardohuang81 ,

The folder `C:\Program Files` contains files and subfolders other than those extracted from data loader's zip file. Data Loader installer tries to copy all of the content of `C:\Program Files` to the installation folder including preexisting files and folders that are not shipped with data loader. It seems that you do not have sufficient access privileges for some of the preexisting subfolders such as `WindowsApps`, which leads to the issue.

The fix is to download the zip file to your Desktop folder:

- Right-click on the zip file and select "Extract All..." from the dropdown menu. 

> <img width="693" alt="Screenshot 2023-08-02 at 9 27 28 PM" src="https://github.com/forcedotcom/dataloader/assets/71143047/e49dbc19-107c-4f9c-a2ad-0a78bf941b66">


- A folder selection dialog is shown with prefilled default folder name. Do not change it.

> <img width="561" alt="Screenshot 2023-08-02 at 9 28 36 PM" src="https://github.com/forcedotcom/dataloader/assets/71143047/782ff2ee-b253-47e4-8c76-92bfc6fd3240">


- Select "Extract". You will see the new folder in your File Explorer.

> <img width="681" alt="Screenshot 2023-08-02 at 9 29 12 PM" src="https://github.com/forcedotcom/dataloader/assets/71143047/ac5daef3-de27-451e-8416-522887f53885">

- Go to the subfolder `dataloader_v58.0.3` and double-click on install.bat to launch it.

**Comment by ricardohuang81** [comment]
@ashitsalesforce, ok I moved the **dataloader_v58.0.3** zip file to my desktop and extracted all to the desktop like you instructed, but after clicking install.bat, the installer in command prompt just quits without giving an explanation after I type "yes" to create a desktop and start menu shortcut, see screenshot below.

![Dataloader](https://github.com/forcedotcom/dataloader/assets/25620842/e32f797b-1d9a-420e-b637-feea6cf87792)

When I double click the **dataloader-58.0.3** jar file in the extracted folder, a dataloader.bat file appears and when clicking that, I could access Data Loader, but there's no shortcut on the desktop or start menu where I could access Data Loader from, see screenshot below.

![Dataloader 2](https://github.com/forcedotcom/dataloader/assets/25620842/683a9f43-2d3d-4fe9-a9d8-4b02a21432d2)

I'm using Windows 11 because it came with the laptop, but I'm not that familiar with it, when I extracted the dataloader zip file, the path showed "One Drive" in it. The **Zulu OpenJDK** folder is also still in C:\Program Files, does that have to be on the desktop too?

**Comment by ashitsalesforce** [comment]
Hi @ricardohuang81 ,

The fact that you are able to successfully launch and access data loader means your Java 17 Runtime is installed correctly and is used to run data loader code. So, no need to change anything regarding Zulu OpenJDK installation folder.

Your data loader installation seems to be successfully completed based on your screenshot. Here is a screenshot of my Windows 11 desktop showing a shortcut on my Desktop screen:
> <img width="468" alt="Screenshot 2023-08-03 at 7 55 01 AM" src="https://github.com/forcedotcom/dataloader/assets/71143047/c1d07d3c-44ae-4f50-874a-404420566fb8">

To see it in Start menu, take the following steps:
- Click on "Start"
> 
<img width="595" alt="Screenshot 2023-08-03 at 7 55 34 AM" src="https://github.com/forcedotcom/dataloader/assets/71143047/8591def3-ad2c-4f64-9cc0-9dc039580ab2">

- Click on "All Apps" and scroll down to Salesforce folder
> 
<img width="609" alt="Screenshot 2023-08-03 at 7 55 58 AM" src="https://github.com/forcedotcom/dataloader/assets/71143047/0bc119c9-043f-4ed2-ba6c-123f5baab6eb">

- Click on Salesforce folder. You will see the shortcut to Data Loader
> 
<img width="606" alt="Screenshot 2023-08-03 at 7 56 10 AM" src="https://github.com/forcedotcom/dataloader/assets/71143047/a3419e4b-e3a2-4bc9-aa6f-8f5cbe7a036b">

**Comment by ricardohuang81** [comment]
@ashitsalesforce, I don't see a **Salesforce** or **dataloader_v58.0.3** folder on the start menu, see screenshots below.

![Start 1](https://github.com/forcedotcom/dataloader/assets/25620842/730f83b5-9504-4f36-8e76-e4cefb2a3732)

![Start 2](https://github.com/forcedotcom/dataloader/assets/25620842/1cc12599-1274-4342-ac62-227f394a42ae)

And the **dataloader_v58.0.3** installation file and extracted file are both on my desktop right now, see screenshot below.

![Desktop](https://github.com/forcedotcom/dataloader/assets/25620842/06afd3e0-b5dd-4eae-9890-8db2fee4b706)

See the path in screenshot below where I extracted the files

![Extract](https://github.com/forcedotcom/dataloader/assets/25620842/667f4685-fa75-4b4e-811f-49fd64b05f58)

**Comment by ashitsalesforce** [comment]
Hi @ricardohuang81 ,

- Go to the folder  `C:\Users\ricky\OneDrive\Desktop\dataloader_v58.0.3` in `File Explorer`.
- Double-click on `install.bat`
- Go through the installation prompts. Answer `Y` to the questions about deleting existing installation folder, creating a Desktop shortcut, and creating a Start menu shortcut.

**Comment by ricardohuang81** [comment]
Hi @ashitsalesforce, yes that's exactly what I did previously and I just did it again, but the command prompt just quits without any type of message or explanation why and there's still nothing on the Start Menu or Desktop, see screenshot below.

![command prompt](https://github.com/forcedotcom/dataloader/assets/25620842/94e3e0b2-94b5-4b21-9a0d-5b3682a3ff5d)

**Comment by ashitsalesforce** [comment]
Hi @ricardohuang81 , not sure why these shortcuts are not being created for you. Likely they are not created because of certain permission settings applied to your desktop. You will need to work with your Windows admin to troubleshoot.

You can try to manually create Desktop and Start menu shortcuts using Windows documentation and information found online such as:
- https://support.microsoft.com/en-us/windows/pin-apps-and-folders-to-the-desktop-or-taskbar-f3c749fb-e298-4cf1-adda-7fd635df6bb0
- https://www.online-tech-tips.com/computer-tips/how-to-add-shortcuts-to-the-windows-start-menu/

**Comment by ricardohuang81** [comment]
@ashitsalesforce, ok I will take a look at those. But I would be the Windows admin because this is my personal laptop, do you have any permission settings in mind that I should try?

**Comment by ashitsalesforce** [comment]
No, I don't. Here is the bat script snippet from [util.bat](https://github.com/forcedotcom/dataloader/blob/master/src/main/resources/win/util/util.bat) that creates the two shortcuts:
```
:CreateShortcut
    powershell -Command "$WshShell = New-Object -comObject WScript.Shell; $Shortcut = $WshShell.CreateShortcut(""""%~1""""); $Shortcut.WorkingDirectory = """"%~2""""; $Shortcut.TargetPath = """"%~2\dataloader.bat""""; $Shortcut.IconLocation = """"%~2\dataloader.ico""""; $Shortcut.WindowStyle=7; $Shortcut.Save()"
    EXIT /b 0

:createStartMenuShortcut
    IF NOT EXIST "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Salesforce\" (
        mkdir "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Salesforce"
    )
    CALL :CreateShortcut "$Home\Desktop\Dataloader.lnk" "$Home\dataloader\v58.0.3\dataloader.bat"
    move "%USERPROFILE%\Desktop\Dataloader.lnk" "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Salesforce\Dataloader %DATALOADER_VERSION%.lnk" >nul
    EXIT /b 0

:createDesktopShortcut
    CALL :CreateShortcut "$Home\Desktop\Dataloader.lnk" "$Home\dataloader\v58.0.3\dataloader.bat"
    for /f "usebackq tokens=3*" %%D IN (`reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v Desktop`) do set DESKTOP_DIR=%%D
    move "%USERPROFILE%\Desktop\Dataloader.lnk" "%DESKTOP_DIR%\Dataloader %DATALOADER_VERSION%.lnk" >nul
    EXIT /b 0
```

**Comment by ricardohuang81** [comment]
@ashitsalesforce, ok thank you.

**Comment by ashitsalesforce** [comment]
Hi @ricardohuang81 , good to see that your issue is resolved. Can you share the fix?

**Comment by ricardohuang81** [comment]
@ashitsalesforce, I just manually created a shortcut from the folder and dragged it onto the desktop. It looks kind of janky because it's not the usual Data Loader logo and I still can't access it on the Start Menu, but I can access Data Loader so that's enough for now, it's not a huge deal if I can't access it on the Start Menu and Desktop shortcut logo is not how it usually looks.

**Comment by ashitsalesforce** [comment]
Hi @ricardohuang81 , thanks for sharing that workaround. Here is the workaround you can try to create a Start menu shortcut:

- create a shortcut to `dataloader.bat` in the data loader installation folder. Name it `Dataloader 58.0.3`
- create the sub-folder `Salesforce`in `C:\Users\ricky\AppData\Roaming\Microsoft\Windows\Start Menu\Programs` folder.
- move the shortcut from the data loader installation folder to `C:\Users\ricky\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Salesforce` folder.
- Go to `Start` menu and search for `Dataloader`.
